M48
; DRILL file {KiCad 6.0.9+dfsg-1~bpo11+1} date Wed Jan  4 12:19:54 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-04T12:19:54+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.800
%
G90
G05
T1
X48.33Y34.575
X48.33Y23.145
T2
X27.33Y34.575
X27.33Y23.145
T3
X18.395Y71.12
X18.395Y33.02
X53.995Y71.12
X53.995Y33.02
T0
M30
